#ifndef CONSTS_H
#define CONSTS_H

#define MAX_LINES (1000)
#define MAX_LABELS (MAX_LINES * 5)

#define MAX_FILENAME_LENGTH (256)
#define MAX_LINE_LENGTH (256)
#define MAX_LABEL_LENGTH (30)
#define INSTRUCTION_NAME_LENGTH (5)

#define DATA_SECTION_MAX_LENGTH (1000)
#define CODE_SECTION_MAX_LENGTH (1000)

#define MAX_DIRECTIVE_NAME_LENGTH (32)

#define COMB_OFFSET (0)
#define DEST_REGISTER_OFFSET (2)
#define DEST_ADDRESS_MODE_OFFSET (5)
#define SRC_REGISTER_OFFSET (7)
#define SRC_ADDRESS_MODE_OFFSET (10)
#define OPCODE_OFFSET (12)
#define TYPE_OFFSET (16)

#define START_OFFSET (100)

#endif /* end of include guard: CONSTS_H */
